# Generated by Django 5.2.4 on 2025-09-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0002_alter_mealtoken_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtoken',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('used', 'Used')], default='pending', max_length=20),
        ),
    ]
