# Generated by Django 5.2.4 on 2025-09-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0003_alter_mealtoken_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtoken',
            name='validity_minutes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
