# Generated by Django 5.2.4 on 2025-09-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0004_alter_mealtoken_validity_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtoken',
            name='validity_minutes',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
