# Generated by Django 5.2.4 on 2025-09-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0005_alter_mealtoken_validity_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('canteenstaff', 'Canteen Staff')], default='user', max_length=15),
        ),
    ]
