# Generated by Django 5.2.4 on 2025-09-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen_app.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='daily_quantity',
            field=models.DecimalField(decimal_places=1, default=0, help_text='How many available today (supports .5 for half-portions)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='has_half',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='max_per_user_per_day',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
