# Generated by Django 5.2.4 on 2025-09-28 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0007_alter_dailyreport_item_alter_menuitem_daily_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={},
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='cancelled_tokens',
            new_name='cancelled_tokens_count',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='collected_count',
            new_name='expired_tokens_count',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='item',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='expired_count',
            new_name='used_tokens_count',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='visible',
            new_name='is_visible',
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('date', 'menu_item')},
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='disable_ordering',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='name',
        ),
        migrations.RemoveField(
            model_name='serving',
            name='item',
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='holiday',
            name='ordering_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='title',
            field=models.CharField(default='General Holiday', max_length=255),
        ),
        migrations.AddField(
            model_name='serving',
            name='item_name',
            field=models.CharField(default='Default Item', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen_app.menuitem'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='9999999999', max_length=20),
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='expired_tokens',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='used_tokens',
        ),
    ]
