# Generated by Django 5.2.4 on 2025-09-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0008_alter_dailyreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_expiry_minutes', models.PositiveIntegerField(default=90)),
                ('auto_expire_tokens', models.BooleanField(default=True)),
                ('qr_payment_auto_use', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Token Settings',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('canteenstaff', 'Canteen Staff'), ('admin', 'Admin')], default='user', max_length=15),
        ),
    ]
