# Generated by Django 5.2.4 on 2025-09-29 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0010_mealtoken_payment_time_mealtoken_upi_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealtoken',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterField(
            model_name='mealtokencounter',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, unique=True),
        ),
    ]
