# Generated by Django 5.2.4 on 2025-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0011_alter_mealtoken_options_alter_mealtokencounter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_failure', 'Payment Failure'), ('system', 'System'), ('info', 'Info')], default='info', max_length=20),
        ),
    ]
