# Generated by Django 5.2.4 on 2025-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0012_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtoken',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
