# Generated by Django 5.2.4 on 2025-10-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0013_mealtoken_payment_verified'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['holiday_date'], name='canteen_app_holiday_202e8e_idx'),
        ),
    ]
