# Generated by Django 5.2.4 on 2025-10-22 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0014_holiday_canteen_app_holiday_202e8e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalfPortion',
            fields=[
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='half_portion', serialize=False, to='canteen_app.menuitem')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for half portion', max_digits=8)),
            ],
            options={
                'verbose_name': 'Half Portion',
                'verbose_name_plural': 'Half Portions',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='serving',
            options={'verbose_name': 'Serving Counter', 'verbose_name_plural': 'Serving Counters'},
        ),
        migrations.RemoveField(
            model_name='mealtoken',
            name='payment_time',
        ),
        migrations.RemoveField(
            model_name='mealtoken',
            name='served_at',
        ),
        migrations.RemoveField(
            model_name='mealtoken',
            name='served_by',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='half_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterUniqueTogether(
            name='serving',
            unique_together={('menu_item',)},
        ),
        migrations.AddField(
            model_name='mealtoken',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When this token becomes valid (for scheduled drinks)', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canteen_app.mealtoken'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preferred_datetime',
            field=models.DateTimeField(blank=True, help_text='When the user wants this item served (optional, use for drinks)', null=True),
        ),
        migrations.AddField(
            model_name='serving',
            name='menu_item',
            field=models.ForeignKey(default=0, help_text='Menu item being served', on_delete=django.db.models.deletion.CASCADE, to='canteen_app.menuitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_success', 'Payment Success'), ('payment_failure', 'Payment Failure'), ('system', 'System'), ('info', 'Info'), ('token_expiring', 'Token Expiring Soon'), ('token_expired', 'Token Expired')], default='info', max_length=20),
        ),
        migrations.CreateModel(
            name='TokenStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='canteen_app.mealtoken')),
            ],
            options={
                'verbose_name': 'Token Status History',
                'verbose_name_plural': 'Token Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='serving',
            name='item_name',
        ),
    ]
