# Generated by Django 5.2.4 on 2025-11-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0015_halfportion_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtoken',
            name='payment_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
