# Generated by Django 5.2.4 on 2025-11-04 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_app', '0016_mealtoken_payment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtoken',
            name='payment_datetime',
        ),
        migrations.AddField(
            model_name='mealtoken',
            name='payment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealtoken',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealtoken',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
